import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Banner from "../components/Banner";
import Description from "../components/Description";
import Photos from "../components/Photos";
import { useRouter } from "next/router";

export default function Home() {
  const [colorAfter, setColorAfter] = useState(false);
  const router = useRouter();
  // const [scrollChange, setScrollChange] = useState(false);
  // const scrollListener = window.addEventListener("scroll", () => {
  //   setScrollChange(true);
  // });

  // function for detect scroll changement and change color

  useEffect(() => {
    // navbar.style.color = "white";
    console.log("index");
    window.addEventListener("scroll", () => {
      const navbar = document.getElementById("navbar");
      if (router.pathname !== "/contact" && window.scrollY > 500) {
        // navbar.style.backgroundColor = "white";
        // navbar.style.color = "black";
        // navbar.style.height = "15vh";
        setColorAfter(true);
      } else if (router.pathname !== "/contact" && window.scrollY < 500) {
        setColorAfter(false);
        // navbar.style.backgroundColor = "rgba(0,0,0,0)";
        // navbar.style.height = "20vh";
        // navbar.style.color = "white";
      }
    });
  }, [router.pathname]);

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ scrollBehavior: "smooth" }}>
        <Navbar colorAfter={colorAfter} setColorAfter={setColorAfter} />
        <Banner />
        <Description />
        <Photos />
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>{" "}
        <div id="first-section" className={styles.Contact_div_description}>
          <h2 className={styles.Contact_h2_title}>Contact</h2>
          <p className={styles.Contact_p_text}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates,
            quisquam.
          </p>
        </div>
        <button onClick={scrollToTop} className={styles.Contact_button}>
          Back to top
        </button>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footer_div_description}>
          <p>Les Caves de la Croix Douillard</p>
          <span className={styles.logo}>
            <Image src="/logo.png" alt="Vercel Logo" width={25} height={25} />
          </span>
        </div>
        <div className={styles.footer_div_footer}>
          <p>
            Copyright © 2022 Les Caves de la Croix Douillard. Tout droit
            réservé.
          </p>
        </div>
      </footer>
    </div>
  );
}
